title: Yashika Raheja# your name (or website title) here
logo: "/my_pic.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Full Stack Developer
  <br><br>
  <a href="mailto:yashikaraheja98@gmail.com">yashikaraheja98@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/yashika-raheja-9a16b5153/">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/yashikaraheja/">Gihub</a> 
  <a href="https://www.codechef.com/users/yashika_raheja">Codechef</a> 
theme: jekyll-theme-minimal
